/*
DNS DTC API

Testing HealthCheckHttpAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dtc

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/infobloxopen/universal-ddi-go-client/dtc"
)

func TestHealthCheckHttpAPIService(t *testing.T) {

	apiClient := dtc.NewAPIClient()

	t.Run("Test HealthCheckHttpAPIService Create", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		body := dtc.NewHTTPHealthCheck("test-hc-http", 80)
		body.SetRequest("GET / HTTP/1.0\r\n\r\n")

		resp, httpRes, err := apiClient.HealthCheckHttpAPI.Create(context.Background()).Body(*body).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthCheckHttpAPIService Delete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		httpRes, err := apiClient.HealthCheckHttpAPI.Delete(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthCheckHttpAPIService List", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.HealthCheckHttpAPI.List(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthCheckHttpAPIService Read", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		resp, httpRes, err := apiClient.HealthCheckHttpAPI.Read(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HealthCheckHttpAPIService Update", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		body := dtc.NewHTTPHealthCheck("test-hc-http-updated", 8080)
		body.SetRequest("GET /health HTTP/1.0\r\n\r\n")

		resp, httpRes, err := apiClient.HealthCheckHttpAPI.Update(context.Background(), id).Body(*body).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
